#!/usr/bin/perl -w

use strict;
use warnings;

my ($infilename, @bad) = @ARGV;
die "Too many arguments " if @bad;
die "missing filename " unless $infilename;
#print "$infilename\n";

my %mem_vars = ();

open INFILE, "<", $infilename or die $!;
while (<INFILE>) {
    while (m!(_dsn_mem_0x[0-9a-fA-F]+)/\*\|([^|]*)\|\*/!g) {
        if (!exists($mem_vars{$1})) {
            $mem_vars{$1} = $2;
        } else {
            die "$1: multiple types " if ($2 ne $mem_vars{$1});
        }
    }
}

open INFILE, "<", $infilename or die $!;
while (<INFILE>) {
    print;
    if (/^int main\(int argc/) {
        for my $key (keys %mem_vars) {
            print "  $mem_vars{$key} $key;\n";
        }
    }
}
