(* auto-generated by gt *)

let parsed =  let lexbuf = Lexing.from_channel stdin in  Smtlib_parse.main Smtlib_lex.token lexbuf;;
match parsed with
  None -> ()
| Some(x) -> Smtlib_pp.pp x;;

print_string "\n";;