type token =
  | EOF
  | AS
  | ASSERT
  | CHECKSAT
  | DECLAREFUN
  | DECLARESORT
  | DEFINEFUN
  | DEFINESORT
  | EXCLIMATIONPT
  | EXISTS
  | EXIT
  | FORALL
  | GETASSERT
  | GETASSIGN
  | GETINFO
  | GETOPTION
  | GETPROOF
  | GETUNSATCORE
  | GETVALUE
  | LET
  | LPAREN
  | POP
  | PUSH
  | RPAREN
  | SETINFO
  | SETLOGIC
  | SETOPTION
  | UNDERSCORE
  | ASCIIWOR of (string)
  | BINARY of (string)
  | DECIMAL of (string)
  | HEXADECIMAL of (string)
  | KEYWORD of (string)
  | NUMERAL of (string)
  | STRINGLIT of (string)
  | SYMBOL of (string)

open Parsing;;
let _ = parse_error;;
# 2 "smtlib_parse.mly"
(* auto-generated by gt *)

   open Smtlib_syntax;;
let parse_error s =
   print_string s;
  print_string " on line ";
  print_int !Smtlib_util.line;
  print_string "\n";;

# 52 "smtlib_parse.ml"
let yytransl_const = [|
    0 (* EOF *);
  257 (* AS *);
  258 (* ASSERT *);
  259 (* CHECKSAT *);
  260 (* DECLAREFUN *);
  261 (* DECLARESORT *);
  262 (* DEFINEFUN *);
  263 (* DEFINESORT *);
  264 (* EXCLIMATIONPT *);
  265 (* EXISTS *);
  266 (* EXIT *);
  267 (* FORALL *);
  268 (* GETASSERT *);
  269 (* GETASSIGN *);
  270 (* GETINFO *);
  271 (* GETOPTION *);
  272 (* GETPROOF *);
  273 (* GETUNSATCORE *);
  274 (* GETVALUE *);
  275 (* LET *);
  276 (* LPAREN *);
  277 (* POP *);
  278 (* PUSH *);
  279 (* RPAREN *);
  280 (* SETINFO *);
  281 (* SETLOGIC *);
  282 (* SETOPTION *);
  283 (* UNDERSCORE *);
    0|]

let yytransl_block = [|
  284 (* ASCIIWOR *);
  285 (* BINARY *);
  286 (* DECIMAL *);
  287 (* HEXADECIMAL *);
  288 (* KEYWORD *);
  289 (* NUMERAL *);
  290 (* STRINGLIT *);
  291 (* SYMBOL *);
    0|]

let yylhs = "\255\255\
\001\000\001\000\031\000\002\000\003\000\003\000\005\000\005\000\
\005\000\006\000\006\000\006\000\006\000\006\000\006\000\006\000\
\006\000\006\000\006\000\006\000\006\000\006\000\006\000\006\000\
\006\000\006\000\006\000\006\000\011\000\013\000\013\000\015\000\
\016\000\016\000\017\000\017\000\017\000\017\000\019\000\019\000\
\020\000\022\000\022\000\022\000\022\000\022\000\023\000\023\000\
\024\000\024\000\024\000\024\000\024\000\024\000\024\000\030\000\
\025\000\025\000\026\000\026\000\027\000\027\000\028\000\028\000\
\029\000\029\000\021\000\021\000\018\000\018\000\014\000\014\000\
\012\000\012\000\010\000\010\000\008\000\008\000\007\000\007\000\
\009\000\009\000\004\000\004\000\000\000"

let yylen = "\002\000\
\001\000\001\000\000\000\001\000\002\000\003\000\001\000\001\000\
\004\000\005\000\005\000\005\000\006\000\009\000\009\000\010\000\
\005\000\005\000\005\000\004\000\004\000\004\000\004\000\007\000\
\004\000\005\000\005\000\004\000\001\000\001\000\006\000\002\000\
\001\000\006\000\001\000\001\000\002\000\004\000\001\000\005\000\
\005\000\002\000\002\000\002\000\002\000\002\000\002\000\002\000\
\001\000\001\000\005\000\008\000\008\000\008\000\006\000\005\000\
\001\000\002\000\001\000\002\000\001\000\002\000\001\000\002\000\
\001\000\002\000\001\000\002\000\001\000\002\000\002\000\003\000\
\001\000\002\000\001\000\002\000\001\000\002\000\001\000\002\000\
\001\000\002\000\001\000\002\000\002\000"

let yydefred = "\000\000\
\000\000\000\000\002\000\085\000\003\000\001\000\029\000\000\000\
\074\000\000\000\003\000\000\000\003\000\003\000\003\000\003\000\
\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\
\000\000\000\000\003\000\003\000\003\000\033\000\050\000\049\000\
\030\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\
\000\000\028\000\021\000\025\000\000\000\000\000\000\000\022\000\
\023\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\
\004\000\019\000\000\000\048\000\046\000\042\000\045\000\043\000\
\044\000\047\000\003\000\000\000\003\000\003\000\027\000\032\000\
\026\000\000\000\000\000\018\000\017\000\012\000\000\000\010\000\
\011\000\003\000\003\000\000\000\000\000\000\000\003\000\003\000\
\000\000\000\000\039\000\003\000\000\000\013\000\000\000\003\000\
\000\000\000\000\003\000\000\000\000\000\076\000\006\000\007\000\
\008\000\000\000\003\000\000\000\003\000\003\000\003\000\003\000\
\003\000\000\000\000\000\000\000\003\000\080\000\000\000\003\000\
\078\000\003\000\003\000\082\000\024\000\003\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\066\000\051\000\000\000\
\003\000\003\000\003\000\000\000\000\000\003\000\035\000\036\000\
\000\000\034\000\058\000\055\000\060\000\003\000\062\000\003\000\
\003\000\064\000\003\000\031\000\000\000\015\000\000\000\000\000\
\000\000\000\000\014\000\009\000\084\000\003\000\037\000\000\000\
\000\000\000\000\003\000\072\000\068\000\040\000\016\000\041\000\
\003\000\000\000\000\000\054\000\053\000\052\000\000\000\070\000\
\038\000\056\000"

let yydgoto = "\002\000\
\004\000\056\000\130\000\149\000\103\000\005\000\090\000\095\000\
\098\000\074\000\006\000\007\000\030\000\140\000\045\000\031\000\
\150\000\186\000\092\000\096\000\168\000\032\000\033\000\075\000\
\131\000\133\000\136\000\137\000\115\000\138\000\035\000"

let yysindex = "\005\000\
\010\000\000\000\000\000\000\000\000\000\000\000\000\000\005\255\
\000\000\187\255\000\000\029\255\000\000\000\000\000\000\000\000\
\030\255\048\255\049\255\000\000\050\255\060\255\066\255\070\255\
\067\255\068\255\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\076\255\123\255\000\000\073\255\230\254\069\255\084\255\
\095\255\000\000\000\000\000\000\094\255\092\255\103\255\000\000\
\000\000\000\000\105\255\109\255\110\255\104\255\115\255\117\255\
\000\000\000\000\022\255\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\118\255\000\000\000\000\000\000\000\000\
\000\000\122\255\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\128\255\130\255\140\255\000\000\000\000\
\016\255\138\255\000\000\000\000\026\255\000\000\142\255\000\000\
\143\255\145\255\000\000\230\254\148\255\000\000\000\000\000\000\
\000\000\006\000\000\000\085\255\000\000\000\000\000\000\000\000\
\000\000\000\000\149\255\002\255\000\000\000\000\147\255\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\152\255\026\255\
\147\255\000\000\153\255\000\000\154\255\143\255\000\000\155\255\
\156\255\000\000\160\255\158\255\150\255\000\000\000\000\162\255\
\000\000\000\000\000\000\164\255\172\255\000\000\000\000\000\000\
\218\255\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\175\255\
\183\255\184\255\000\000\000\000\000\000\000\000\000\000\191\255\
\192\255\193\255\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\195\255\218\255\000\000\000\000\000\000\198\255\000\000\
\000\000\000\000"

let yyrindex = "\000\000\
\001\000\000\000\000\000\000\000\000\000\000\000\000\000\196\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\107\255\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\234\255\000\000\000\000\000\000\197\255\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\199\255\000\000\000\000\000\000\
\109\255\000\000\000\000\117\255\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\250\255\000\000\000\000\000\000\000\000\107\255\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\033\255\000\000\025\255\000\000\000\000\047\255\000\000\
\000\000\057\255\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\201\255\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\244\254\000\000\015\255\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000\210\255\000\000\000\000\000\000\000\000\000\000\
\000\000\000\000"

let yygindex = "\000\000\
\000\000\000\000\067\000\069\000\000\000\000\000\143\000\140\000\
\138\000\164\000\000\000\235\000\196\255\076\000\000\000\183\000\
\087\255\058\000\173\255\163\255\077\000\185\255\060\000\009\000\
\125\000\124\000\123\000\121\000\146\000\000\000\255\255"

let yytablesize = 297
let yytable = "\008\000\
\003\000\060\000\082\000\008\000\185\000\001\000\091\000\104\000\
\066\000\003\000\071\000\038\000\038\000\038\000\038\000\185\000\
\132\000\135\000\046\000\034\000\003\000\107\000\082\000\127\000\
\010\000\054\000\038\000\054\000\087\000\083\000\084\000\091\000\
\085\000\144\000\003\000\116\000\146\000\067\000\132\000\148\000\
\086\000\135\000\003\000\060\000\003\000\119\000\091\000\059\000\
\087\000\003\000\066\000\036\000\042\000\060\000\151\000\057\000\
\091\000\089\000\145\000\091\000\066\000\167\000\091\000\170\000\
\003\000\093\000\003\000\097\000\100\000\061\000\043\000\044\000\
\037\000\039\000\040\000\041\000\003\000\106\000\151\000\063\000\
\108\000\047\000\048\000\167\000\091\000\038\000\091\000\055\000\
\049\000\050\000\093\000\109\000\067\000\053\000\097\000\057\000\
\114\000\100\000\058\000\051\000\052\000\068\000\151\000\069\000\
\129\000\128\000\091\000\054\000\134\000\134\000\139\000\141\000\
\060\000\151\000\070\000\128\000\071\000\108\000\128\000\066\000\
\038\000\128\000\114\000\072\000\153\000\073\000\003\000\076\000\
\054\000\099\000\134\000\077\000\078\000\134\000\003\000\079\000\
\139\000\080\000\105\000\081\000\094\000\003\000\059\000\128\000\
\101\000\128\000\113\000\110\000\153\000\111\000\060\000\061\000\
\062\000\063\000\169\000\064\000\065\000\066\000\099\000\112\000\
\117\000\038\000\122\000\141\000\120\000\128\000\176\000\123\000\
\177\000\178\000\125\000\143\000\187\000\087\000\154\000\156\000\
\158\000\160\000\161\000\163\000\164\000\147\000\165\000\187\000\
\166\000\152\000\171\000\191\000\011\000\012\000\013\000\014\000\
\015\000\016\000\172\000\073\000\017\000\182\000\018\000\019\000\
\020\000\021\000\022\000\023\000\024\000\183\000\184\000\025\000\
\026\000\152\000\027\000\028\000\029\000\188\000\189\000\190\000\
\003\000\193\000\173\000\005\000\194\000\079\000\179\000\083\000\
\003\000\003\000\003\000\003\000\005\000\003\000\003\000\003\000\
\069\000\152\000\118\000\121\000\124\000\174\000\102\000\009\000\
\180\000\088\000\192\000\181\000\152\000\060\000\061\000\062\000\
\063\000\175\000\064\000\065\000\066\000\003\000\155\000\157\000\
\075\000\159\000\162\000\142\000\000\000\003\000\003\000\003\000\
\003\000\000\000\003\000\003\000\003\000\003\000\000\000\000\000\
\065\000\000\000\000\000\000\000\003\000\003\000\003\000\003\000\
\003\000\126\000\003\000\003\000\003\000\000\000\000\000\000\000\
\000\000\060\000\061\000\062\000\063\000\000\000\064\000\065\000\
\066\000"

let yycheck = "\001\000\
\000\000\028\001\001\001\005\000\174\000\001\000\067\000\079\000\
\035\001\000\000\023\001\013\000\014\000\015\000\016\000\185\000\
\110\000\111\000\020\000\011\000\033\001\082\000\001\001\107\000\
\020\001\027\000\028\000\029\000\027\001\008\001\009\001\092\000\
\011\001\117\000\020\001\020\001\120\000\023\001\132\000\123\000\
\019\001\135\000\028\001\028\001\020\001\020\001\107\000\023\001\
\027\001\035\001\035\001\023\001\023\001\028\001\126\000\023\001\
\117\000\059\000\119\000\120\000\035\001\145\000\123\000\147\000\
\032\001\067\000\020\001\069\000\070\000\023\001\023\001\023\001\
\013\000\014\000\015\000\016\000\020\001\079\000\150\000\023\001\
\082\000\032\001\023\001\167\000\145\000\087\000\147\000\028\000\
\023\001\020\001\092\000\083\000\020\001\027\000\096\000\029\000\
\088\000\099\000\023\001\033\001\033\001\033\001\174\000\020\001\
\020\001\107\000\167\000\109\000\110\000\111\000\112\000\113\000\
\028\001\185\000\020\001\117\000\023\001\119\000\120\000\035\001\
\122\000\123\000\114\000\032\001\126\000\023\001\020\001\023\001\
\130\000\070\000\132\000\023\001\023\001\135\000\028\001\032\001\
\138\000\023\001\079\000\023\001\023\001\035\001\020\001\145\000\
\023\001\147\000\087\000\020\001\150\000\020\001\028\001\029\001\
\030\001\031\001\146\000\033\001\034\001\035\001\099\000\020\001\
\023\001\163\000\020\001\165\000\023\001\167\000\158\000\023\001\
\160\000\161\000\023\001\023\001\174\000\027\001\023\001\023\001\
\023\001\023\001\023\001\020\001\023\001\122\000\033\001\185\000\
\023\001\126\000\023\001\179\000\002\001\003\001\004\001\005\001\
\006\001\007\001\023\001\000\000\010\001\023\001\012\001\013\001\
\014\001\015\001\016\001\017\001\018\001\023\001\023\001\021\001\
\022\001\150\000\024\001\025\001\026\001\023\001\023\001\023\001\
\020\001\023\001\150\000\023\001\023\001\023\001\163\000\023\001\
\028\001\029\001\030\001\031\001\032\001\033\001\034\001\035\001\
\023\001\174\000\092\000\096\000\099\000\020\001\075\000\005\000\
\165\000\059\000\185\000\167\000\185\000\028\001\029\001\030\001\
\031\001\032\001\033\001\034\001\035\001\020\001\130\000\132\000\
\023\001\135\000\138\000\114\000\255\255\028\001\029\001\030\001\
\031\001\255\255\033\001\034\001\035\001\020\001\255\255\255\255\
\023\001\255\255\255\255\255\255\020\001\028\001\029\001\030\001\
\031\001\020\001\033\001\034\001\035\001\255\255\255\255\255\255\
\255\255\028\001\029\001\030\001\031\001\255\255\033\001\034\001\
\035\001"

let yynames_const = "\
  EOF\000\
  AS\000\
  ASSERT\000\
  CHECKSAT\000\
  DECLAREFUN\000\
  DECLARESORT\000\
  DEFINEFUN\000\
  DEFINESORT\000\
  EXCLIMATIONPT\000\
  EXISTS\000\
  EXIT\000\
  FORALL\000\
  GETASSERT\000\
  GETASSIGN\000\
  GETINFO\000\
  GETOPTION\000\
  GETPROOF\000\
  GETUNSATCORE\000\
  GETVALUE\000\
  LET\000\
  LPAREN\000\
  POP\000\
  PUSH\000\
  RPAREN\000\
  SETINFO\000\
  SETLOGIC\000\
  SETOPTION\000\
  UNDERSCORE\000\
  "

let yynames_block = "\
  ASCIIWOR\000\
  BINARY\000\
  DECIMAL\000\
  HEXADECIMAL\000\
  KEYWORD\000\
  NUMERAL\000\
  STRINGLIT\000\
  SYMBOL\000\
  "

let yyact = [|
  (fun _ -> failwith "parser")
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commands) in
    Obj.repr(
# 83 "smtlib_parse.mly"
           ( Some(_1) )
# 344 "smtlib_parse.ml"
               : Smtlib_syntax.commands option))
; (fun __caml_parser_env ->
    Obj.repr(
# 84 "smtlib_parse.mly"
      ( None )
# 350 "smtlib_parse.ml"
               : Smtlib_syntax.commands option))
; (fun __caml_parser_env ->
    Obj.repr(
# 87 "smtlib_parse.mly"
  ( Smtlib_util.cur_pd() )
# 356 "smtlib_parse.ml"
               : Smtlib_util.pd))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.attribute) in
    Obj.repr(
# 90 "smtlib_parse.mly"
            ( AnOptionAttribute(pd_attribute _1, _1) )
# 363 "smtlib_parse.ml"
               : Smtlib_syntax.an_option))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 93 "smtlib_parse.mly"
                       ( AttributeKeyword(_1, _2) )
# 371 "smtlib_parse.ml"
               : Smtlib_syntax.attribute))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 1 : string) in
    let _3 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.attributevalue) in
    Obj.repr(
# 96 "smtlib_parse.mly"
                                      ( AttributeKeywordValue(_1, _2, _3) )
# 380 "smtlib_parse.ml"
               : Smtlib_syntax.attribute))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.specconstant) in
    Obj.repr(
# 99 "smtlib_parse.mly"
               ( AttributeValSpecConst(pd_specconstant _1, _1) )
# 387 "smtlib_parse.ml"
               : Smtlib_syntax.attributevalue))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.symbol) in
    Obj.repr(
# 102 "smtlib_parse.mly"
         ( AttributeValSymbol(pd_symbol _1, _1) )
# 394 "smtlib_parse.ml"
               : Smtlib_syntax.attributevalue))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    let _3 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.attributevalsexpr_attributevalue_sexpr5) in
    Obj.repr(
# 105 "smtlib_parse.mly"
                                                                     ( AttributeValSexpr(_1, _3) )
# 402 "smtlib_parse.ml"
               : Smtlib_syntax.attributevalue))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.symbol) in
    Obj.repr(
# 108 "smtlib_parse.mly"
                                             ( CommandSetLogic(_1, _4) )
# 410 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.an_option) in
    Obj.repr(
# 111 "smtlib_parse.mly"
                                                 ( CommandSetOption(_1, _4) )
# 418 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.attribute) in
    Obj.repr(
# 114 "smtlib_parse.mly"
                                               ( CommandSetInfo(_1, _4) )
# 426 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 5 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.symbol) in
    let _5 = (Parsing.peek_val __caml_parser_env 1 : string) in
    Obj.repr(
# 117 "smtlib_parse.mly"
                                                        ( CommandDeclareSort(_1, _4, _5) )
# 435 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 8 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 5 : Smtlib_syntax.symbol) in
    let _6 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_syntax.commanddefinesort_command_symbol11) in
    let _8 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sort) in
    Obj.repr(
# 120 "smtlib_parse.mly"
                                                                                                     ( CommandDefineSort(_1, _4, _6, _8) )
# 445 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 8 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 5 : Smtlib_syntax.symbol) in
    let _6 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_syntax.commanddeclarefun_command_sort13) in
    let _8 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sort) in
    Obj.repr(
# 123 "smtlib_parse.mly"
                                                                                                   ( CommandDeclareFun(_1, _4, _6, _8) )
# 455 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 9 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 6 : Smtlib_syntax.symbol) in
    let _6 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_syntax.commanddefinefun_command_sortedvar15) in
    let _8 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.sort) in
    let _9 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    Obj.repr(
# 126 "smtlib_parse.mly"
                                                                                                           ( CommandDefineFun(_1, _4, _6, _8, _9) )
# 466 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : string) in
    Obj.repr(
# 129 "smtlib_parse.mly"
                                          ( CommandPush(_1, _4) )
# 474 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : string) in
    Obj.repr(
# 132 "smtlib_parse.mly"
                                         ( CommandPop(_1, _4) )
# 482 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    Obj.repr(
# 135 "smtlib_parse.mly"
                                         ( CommandAssert(_1, _4) )
# 490 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    Obj.repr(
# 138 "smtlib_parse.mly"
                                      ( CommandCheckSat(_1) )
# 497 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    Obj.repr(
# 141 "smtlib_parse.mly"
                                       ( CommandGetAssert(_1) )
# 504 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    Obj.repr(
# 144 "smtlib_parse.mly"
                                      ( CommandGetProof(_1) )
# 511 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    Obj.repr(
# 147 "smtlib_parse.mly"
                                          ( CommandGetUnsatCore(_1) )
# 518 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 6 : Smtlib_util.pd) in
    let _5 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.commandgetvalue_command_term24) in
    Obj.repr(
# 150 "smtlib_parse.mly"
                                                                                   ( CommandGetValue(_1, _5) )
# 526 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    Obj.repr(
# 153 "smtlib_parse.mly"
                                       ( CommandGetAssign(_1) )
# 533 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : string) in
    Obj.repr(
# 156 "smtlib_parse.mly"
                                               ( CommandGetOption(_1, _4) )
# 541 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.infoflag) in
    Obj.repr(
# 159 "smtlib_parse.mly"
                                              ( CommandGetInfo(_1, _4) )
# 549 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    Obj.repr(
# 162 "smtlib_parse.mly"
                                  ( CommandExit(_1) )
# 556 "smtlib_parse.ml"
               : Smtlib_syntax.command))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commands_commands_command30) in
    Obj.repr(
# 165 "smtlib_parse.mly"
                              ( Commands(pd_commands_commands_command30 _1, _1) )
# 563 "smtlib_parse.ml"
               : Smtlib_syntax.commands))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.symbol) in
    Obj.repr(
# 168 "smtlib_parse.mly"
         ( IdSymbol(pd_symbol _1, _1) )
# 570 "smtlib_parse.ml"
               : Smtlib_syntax.identifier))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 5 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.symbol) in
    let _5 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.idunderscoresymnum_identifier_numeral33) in
    Obj.repr(
# 171 "smtlib_parse.mly"
                                                                                       ( IdUnderscoreSymNum(_1, _4, _5) )
# 579 "smtlib_parse.ml"
               : Smtlib_syntax.identifier))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 174 "smtlib_parse.mly"
                       ( InfoFlagKeyword(_1, _2) )
# 587 "smtlib_parse.ml"
               : Smtlib_syntax.infoflag))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.identifier) in
    Obj.repr(
# 177 "smtlib_parse.mly"
             ( QualIdentifierId(pd_identifier _1, _1) )
# 594 "smtlib_parse.ml"
               : Smtlib_syntax.qualidentifier))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 5 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.identifier) in
    let _5 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sort) in
    Obj.repr(
# 180 "smtlib_parse.mly"
                                                ( QualIdentifierAs(_1, _4, _5) )
# 603 "smtlib_parse.ml"
               : Smtlib_syntax.qualidentifier))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.specconstant) in
    Obj.repr(
# 183 "smtlib_parse.mly"
               ( SexprSpecConst(pd_specconstant _1, _1) )
# 610 "smtlib_parse.ml"
               : Smtlib_syntax.sexpr))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.symbol) in
    Obj.repr(
# 186 "smtlib_parse.mly"
         ( SexprSymbol(pd_symbol _1, _1) )
# 617 "smtlib_parse.ml"
               : Smtlib_syntax.sexpr))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 189 "smtlib_parse.mly"
                       ( SexprKeyword(_1, _2) )
# 625 "smtlib_parse.ml"
               : Smtlib_syntax.sexpr))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_util.pd) in
    let _3 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sexprinparen_sexpr_sexpr41) in
    Obj.repr(
# 192 "smtlib_parse.mly"
                                                        ( SexprInParen(_1, _3) )
# 633 "smtlib_parse.ml"
               : Smtlib_syntax.sexpr))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.identifier) in
    Obj.repr(
# 195 "smtlib_parse.mly"
             ( SortIdentifier(pd_identifier _1, _1) )
# 640 "smtlib_parse.ml"
               : Smtlib_syntax.sort))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _3 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.identifier) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sortidsortmulti_sort_sort44) in
    Obj.repr(
# 198 "smtlib_parse.mly"
                                                                    ( SortIdSortMulti(_1, _3, _4) )
# 649 "smtlib_parse.ml"
               : Smtlib_syntax.sort))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _3 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.symbol) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sort) in
    Obj.repr(
# 201 "smtlib_parse.mly"
                                         ( SortedVarSymSort(_1, _3, _4) )
# 658 "smtlib_parse.ml"
               : Smtlib_syntax.sortedvar))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 204 "smtlib_parse.mly"
                       ( SpecConstsDec(_1, _2) )
# 666 "smtlib_parse.ml"
               : Smtlib_syntax.specconstant))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 207 "smtlib_parse.mly"
                       ( SpecConstNum(_1, _2) )
# 674 "smtlib_parse.ml"
               : Smtlib_syntax.specconstant))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 210 "smtlib_parse.mly"
                         ( SpecConstString(_1, _2) )
# 682 "smtlib_parse.ml"
               : Smtlib_syntax.specconstant))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 213 "smtlib_parse.mly"
                           ( SpecConstsHex(_1, _2) )
# 690 "smtlib_parse.ml"
               : Smtlib_syntax.specconstant))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 216 "smtlib_parse.mly"
                      ( SpecConstsBinary(_1, _2) )
# 698 "smtlib_parse.ml"
               : Smtlib_syntax.specconstant))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 219 "smtlib_parse.mly"
                      ( Symbol(_1, _2) )
# 706 "smtlib_parse.ml"
               : Smtlib_syntax.symbol))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 222 "smtlib_parse.mly"
                        ( SymbolWithOr(_1, _2) )
# 714 "smtlib_parse.ml"
               : Smtlib_syntax.symbol))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.specconstant) in
    Obj.repr(
# 225 "smtlib_parse.mly"
               ( TermSpecConst(pd_specconstant _1, _1) )
# 721 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.qualidentifier) in
    Obj.repr(
# 228 "smtlib_parse.mly"
                 ( TermQualIdentifier(pd_qualidentifier _1, _1) )
# 728 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _3 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.qualidentifier) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.termqualidterm_term_term56) in
    Obj.repr(
# 231 "smtlib_parse.mly"
                                                                       ( TermQualIdTerm(_1, _3, _4) )
# 737 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 7 : Smtlib_util.pd) in
    let _5 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_syntax.termletterm_term_varbinding58) in
    let _7 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    Obj.repr(
# 234 "smtlib_parse.mly"
                                                                                  ( TermLetTerm(_1, _5, _7) )
# 746 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 7 : Smtlib_util.pd) in
    let _5 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_syntax.termforallterm_term_sortedvar60) in
    let _7 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    Obj.repr(
# 237 "smtlib_parse.mly"
                                                                                       ( TermForAllTerm(_1, _5, _7) )
# 755 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 7 : Smtlib_util.pd) in
    let _5 = (Parsing.peek_val __caml_parser_env 3 : Smtlib_syntax.termexiststerm_term_sortedvar62) in
    let _7 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    Obj.repr(
# 240 "smtlib_parse.mly"
                                                                                       ( TermExistsTerm(_1, _5, _7) )
# 764 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 5 : Smtlib_util.pd) in
    let _4 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.term) in
    let _5 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.termexclimationpt_term_attribute64) in
    Obj.repr(
# 243 "smtlib_parse.mly"
                                                                                   ( TermExclimationPt(_1, _4, _5) )
# 773 "smtlib_parse.ml"
               : Smtlib_syntax.term))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 4 : Smtlib_util.pd) in
    let _3 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_syntax.symbol) in
    let _4 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    Obj.repr(
# 246 "smtlib_parse.mly"
                                         ( VarBindingSymTerm(_1, _3, _4) )
# 782 "smtlib_parse.ml"
               : Smtlib_syntax.varbinding))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.attribute) in
    Obj.repr(
# 249 "smtlib_parse.mly"
            ( (pd_attribute _1, (_1)::[]) )
# 789 "smtlib_parse.ml"
               : Smtlib_syntax.termexclimationpt_term_attribute64))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.attribute) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.termexclimationpt_term_attribute64) in
    Obj.repr(
# 252 "smtlib_parse.mly"
                                               ( let (p, ( l1 )) = _2 in (pd_attribute _1, (_1)::(l1)) )
# 797 "smtlib_parse.ml"
               : Smtlib_syntax.termexclimationpt_term_attribute64))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.sortedvar) in
    Obj.repr(
# 255 "smtlib_parse.mly"
            ( (pd_sortedvar _1, (_1)::[]) )
# 804 "smtlib_parse.ml"
               : Smtlib_syntax.termexiststerm_term_sortedvar62))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sortedvar) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.termexiststerm_term_sortedvar62) in
    Obj.repr(
# 258 "smtlib_parse.mly"
                                            ( let (p, ( l1 )) = _2 in (pd_sortedvar _1, (_1)::(l1)) )
# 812 "smtlib_parse.ml"
               : Smtlib_syntax.termexiststerm_term_sortedvar62))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.sortedvar) in
    Obj.repr(
# 261 "smtlib_parse.mly"
            ( (pd_sortedvar _1, (_1)::[]) )
# 819 "smtlib_parse.ml"
               : Smtlib_syntax.termforallterm_term_sortedvar60))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sortedvar) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.termforallterm_term_sortedvar60) in
    Obj.repr(
# 264 "smtlib_parse.mly"
                                            ( let (p, ( l1 )) = _2 in (pd_sortedvar _1, (_1)::(l1)) )
# 827 "smtlib_parse.ml"
               : Smtlib_syntax.termforallterm_term_sortedvar60))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.varbinding) in
    Obj.repr(
# 267 "smtlib_parse.mly"
             ( (pd_varbinding _1, (_1)::[]) )
# 834 "smtlib_parse.ml"
               : Smtlib_syntax.termletterm_term_varbinding58))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.varbinding) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.termletterm_term_varbinding58) in
    Obj.repr(
# 270 "smtlib_parse.mly"
                                           ( let (p, ( l1 )) = _2 in (pd_varbinding _1, (_1)::(l1)) )
# 842 "smtlib_parse.ml"
               : Smtlib_syntax.termletterm_term_varbinding58))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.term) in
    Obj.repr(
# 273 "smtlib_parse.mly"
       ( (pd_term _1, (_1)::[]) )
# 849 "smtlib_parse.ml"
               : Smtlib_syntax.termqualidterm_term_term56))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.termqualidterm_term_term56) in
    Obj.repr(
# 276 "smtlib_parse.mly"
                                  ( let (p, ( l1 )) = _2 in (pd_term _1, (_1)::(l1)) )
# 857 "smtlib_parse.ml"
               : Smtlib_syntax.termqualidterm_term_term56))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.sort) in
    Obj.repr(
# 279 "smtlib_parse.mly"
       ( (pd_sort _1, (_1)::[]) )
# 864 "smtlib_parse.ml"
               : Smtlib_syntax.sortidsortmulti_sort_sort44))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sort) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.sortidsortmulti_sort_sort44) in
    Obj.repr(
# 282 "smtlib_parse.mly"
                                   ( let (p, ( l1 )) = _2 in (pd_sort _1, (_1)::(l1)) )
# 872 "smtlib_parse.ml"
               : Smtlib_syntax.sortidsortmulti_sort_sort44))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_util.pd) in
    Obj.repr(
# 285 "smtlib_parse.mly"
               ( (_1, []) )
# 879 "smtlib_parse.ml"
               : Smtlib_syntax.sexprinparen_sexpr_sexpr41))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sexpr) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.sexprinparen_sexpr_sexpr41) in
    Obj.repr(
# 288 "smtlib_parse.mly"
                                   ( let (p, ( l1 )) = _2 in (pd_sexpr _1, (_1)::(l1)) )
# 887 "smtlib_parse.ml"
               : Smtlib_syntax.sexprinparen_sexpr_sexpr41))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : string) in
    Obj.repr(
# 291 "smtlib_parse.mly"
                       ( (_1, (_2)::[]) )
# 895 "smtlib_parse.ml"
               : Smtlib_syntax.idunderscoresymnum_identifier_numeral33))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 2 : Smtlib_util.pd) in
    let _2 = (Parsing.peek_val __caml_parser_env 1 : string) in
    let _3 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.idunderscoresymnum_identifier_numeral33) in
    Obj.repr(
# 294 "smtlib_parse.mly"
                                                               ( let (p, ( l1 )) = _3 in (_1, (_2)::(l1)) )
# 904 "smtlib_parse.ml"
               : Smtlib_syntax.idunderscoresymnum_identifier_numeral33))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_util.pd) in
    Obj.repr(
# 297 "smtlib_parse.mly"
               ( (_1, []) )
# 911 "smtlib_parse.ml"
               : Smtlib_syntax.commands_commands_command30))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.command) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commands_commands_command30) in
    Obj.repr(
# 300 "smtlib_parse.mly"
                                      ( let (p, ( l1 )) = _2 in (pd_command _1, (_1)::(l1)) )
# 919 "smtlib_parse.ml"
               : Smtlib_syntax.commands_commands_command30))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.term) in
    Obj.repr(
# 303 "smtlib_parse.mly"
       ( (pd_term _1, (_1)::[]) )
# 926 "smtlib_parse.ml"
               : Smtlib_syntax.commandgetvalue_command_term24))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.term) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commandgetvalue_command_term24) in
    Obj.repr(
# 306 "smtlib_parse.mly"
                                      ( let (p, ( l1 )) = _2 in (pd_term _1, (_1)::(l1)) )
# 934 "smtlib_parse.ml"
               : Smtlib_syntax.commandgetvalue_command_term24))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_util.pd) in
    Obj.repr(
# 309 "smtlib_parse.mly"
               ( (_1, []) )
# 941 "smtlib_parse.ml"
               : Smtlib_syntax.commanddefinefun_command_sortedvar15))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sortedvar) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commanddefinefun_command_sortedvar15) in
    Obj.repr(
# 312 "smtlib_parse.mly"
                                                 ( let (p, ( l1 )) = _2 in (pd_sortedvar _1, (_1)::(l1)) )
# 949 "smtlib_parse.ml"
               : Smtlib_syntax.commanddefinefun_command_sortedvar15))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_util.pd) in
    Obj.repr(
# 315 "smtlib_parse.mly"
               ( (_1, []) )
# 956 "smtlib_parse.ml"
               : Smtlib_syntax.commanddeclarefun_command_sort13))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sort) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commanddeclarefun_command_sort13) in
    Obj.repr(
# 318 "smtlib_parse.mly"
                                        ( let (p, ( l1 )) = _2 in (pd_sort _1, (_1)::(l1)) )
# 964 "smtlib_parse.ml"
               : Smtlib_syntax.commanddeclarefun_command_sort13))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_util.pd) in
    Obj.repr(
# 321 "smtlib_parse.mly"
               ( (_1, []) )
# 971 "smtlib_parse.ml"
               : Smtlib_syntax.commanddefinesort_command_symbol11))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.symbol) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.commanddefinesort_command_symbol11) in
    Obj.repr(
# 324 "smtlib_parse.mly"
                                            ( let (p, ( l1 )) = _2 in (pd_symbol _1, (_1)::(l1)) )
# 979 "smtlib_parse.ml"
               : Smtlib_syntax.commanddefinesort_command_symbol11))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_util.pd) in
    Obj.repr(
# 327 "smtlib_parse.mly"
               ( (_1, []) )
# 986 "smtlib_parse.ml"
               : Smtlib_syntax.attributevalsexpr_attributevalue_sexpr5))
; (fun __caml_parser_env ->
    let _1 = (Parsing.peek_val __caml_parser_env 1 : Smtlib_syntax.sexpr) in
    let _2 = (Parsing.peek_val __caml_parser_env 0 : Smtlib_syntax.attributevalsexpr_attributevalue_sexpr5) in
    Obj.repr(
# 330 "smtlib_parse.mly"
                                                ( let (p, ( l1 )) = _2 in (pd_sexpr _1, (_1)::(l1)) )
# 994 "smtlib_parse.ml"
               : Smtlib_syntax.attributevalsexpr_attributevalue_sexpr5))
(* Entry main *)
; (fun __caml_parser_env -> raise (Parsing.YYexit (Parsing.peek_val __caml_parser_env 0)))
|]
let yytables =
  { Parsing.actions=yyact;
    Parsing.transl_const=yytransl_const;
    Parsing.transl_block=yytransl_block;
    Parsing.lhs=yylhs;
    Parsing.len=yylen;
    Parsing.defred=yydefred;
    Parsing.dgoto=yydgoto;
    Parsing.sindex=yysindex;
    Parsing.rindex=yyrindex;
    Parsing.gindex=yygindex;
    Parsing.tablesize=yytablesize;
    Parsing.table=yytable;
    Parsing.check=yycheck;
    Parsing.error_function=parse_error;
    Parsing.names_const=yynames_const;
    Parsing.names_block=yynames_block }
let main (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables 1 lexfun lexbuf : Smtlib_syntax.commands option)
