(* auto-generated by gt *)


let run () = 
  let lexbuf = Lexing.from_channel stdin in
  let parsed = Smtlib_parse.main Smtlib_lex.token lexbuf in
  (match parsed with
  |  None -> ()
  | Some(x) -> Smtlib_pp.pp x);
  print_string "\n";;

run()
