(* auto-generated by gt *)

let testmode = false

let run () = 
  (* For now, just cheat and assume that all vars have type int *)
  let typemap t =
    if t = "rd" || t = "wr"
    then SmtSimpleAst.BoolSort
    else SmtSimpleAst.IntSort
  in
  let open SmtLibSyntax in
  match SmtLibSolver.read_from_chan stdin with
  | SingleTerm t -> 
    let f = SmtSimplifierLibConverter.smtSimpleofSmtLib typemap t in
    let beaut = SmtSimplePasses.beautify_formula f in
    print_endline (SmtSimpleFns.string_of_term beaut)
  | _ -> failwith "not handeling this yet"
    
let () = if testmode then SmtSimplePasses.test () else run()
