/* define FAULTY_F_KL_1 */
/* define FAULTY_F_KL_2 */
/* define FAULTY_F_KL_4 */
/* define FAULTY_F_KL_6 */
/* define FAULTY_F_KL_7 */
/* define FAULTY_F_KL_8 */
/* define FAULTY_F_KL_10 */
/* define FAULTY_F_KP_1 */
/* define FAULTY_F_KP_2 */
/* define FAULTY_F_KP_3 */
/* define FAULTY_F_KP_4 */
/* define FAULTY_F_KP_5 */
